# Generated by Django 4.0.1 on 2022-03-23 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=255)),
                ('authorNotes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'authorname',
                'db_table': 'authorname',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=255)),
                ('genreDescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'genrenames',
                'db_table': 'genrename',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookTitle', models.CharField(max_length=255)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('bookNotes', models.TextField(blank=True, null=True)),
                ('authorName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookcase.author')),
                ('genreName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookcase.genre')),
            ],
            options={
                'verbose_name_plural': 'books',
                'db_table': 'book',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='genreName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookcase.genre'),
        ),
    ]
